server:
  port: 8088
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456
#      max-active: 20
#      max-wait: 6000
#      min-idle: 1
#      test-on-borrow: true
#      test-on-return: true
Mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml  #这个文件夹要一个个创建
  config-location: classpath:mybatis-config.xml

#db:
#  mysql:
#    location: D:/code/spring/repository/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "123456" #数字注意一定要有""包围 eg:"123456"
    type: com.alibaba.druid.pool.DruidDataSource
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
