spring:
  profiles:
    active: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_name?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456

